version: '3.8'

services:
  laravel-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel-api
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel-api
    networks:
      - laravel

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - ./.env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - laravel

  npm:
    image: node:18
    container_name: npm
    working_dir: /var/www
    volumes:
      - ./:/var/www
    command: ["sleep", "infinity"]
    networks:
      - laravel

volumes:
  db_data:

networks:
  laravel:
    driver: bridge
